JSON_SMTP_SERVER = "SMTP_SERVER"
JSON_SMTP_PORT = "SMTP_PORT"
JSON_SMTP_USER = "SMTP_USER"
JSON_SMTP_PASSWD = "SMTP_PASSWD"
JSON_SMTP_RECV = "SMTP_RECV"
JSON_SMTP_FROM = "SMTP_FROM"


JSON_GLOBAL_MONITOR = 'glb_monitor'
JSON_GLB_MEASURMENTS = "measurements"
JSON_GLB_TRIGGER_THRE = "trigger_thre"
JSON_GLB_UNTRIGGER_TIME = "untrigger_time"
